apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: automatisk-generalisering
  tags:
    - private
spec:
  type: service
  lifecycle: production
  owner: automatisk_generalisering
  system: system:default/automatisk_generalisering
